export const ABOUT_US = "/about-us";
export const HOME = "/";
const PRE_INFO = "/info";
export const INFO = `${PRE_INFO}/:tab`;
export const TECHNOLOGY_URL = `${PRE_INFO}/technology`;
export const SERVICES_INFO = `${PRE_INFO}/services`;
export const PRODUCTS_URL = `${PRE_INFO}/products`;
export const CLIENTS_URL = `${PRE_INFO}/clients`;
export const PROCESS_URL = `${PRE_INFO}/process`;
